apiVersion: v1
kind: Service
metadata:
  name: cloud-demo
  namespace: cloud-demo
spec:
  type: NodePort
  selector:
    app: cloud-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
