name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout repo
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Lint (basic check with flake8)
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 smallwebapp.py --max-line-length=120

    # Build Docker image
    - name: Build Docker image
      run: |
        docker build -t cloud-demo:ci .

    # (Optional) Run tests if you add a tests/ directory
    - name: Run tests
      if: hashFiles('tests/**/*.py') != ''
      run: |
        pytest -v
