name: Kubernetes Deployment Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  minikube-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Install dependencies Minikube needs
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y conntrack socat

    # Install Minikube and kubectl
    - name: Install Minikube and kubectl
      run: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube /usr/local/bin/
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install kubectl /usr/local/bin/

    # Start Minikube in none-driver mode
    - name: Start Minikube
      run: |
        sudo minikube start --driver=none --kubernetes-version=v1.29.0 --wait=all
        kubectl cluster-info
        kubectl get nodes

    # Build Docker image inside Minikube environment
    - name: Build Docker image inside Minikube
      run: |
        eval $(minikube docker-env)
        docker build -t cloud-demo:local .

    # Deploy manifests
    - name: Deploy app to Minikube
      run: |
        kubectl apply -f namespace.yaml
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl rollout status deployment/cloud-demo -n cloud-demo

    # Test service via NodePort
    - name: Test service
      run: |
        kubectl wait --for=condition=available deployment/cloud-demo -n cloud-demo --timeout=120s
        NODE_IP=$(minikube ip)
        curl -v http://$NODE_IP:30080
