name: Kubernetes Deployment Test (kind)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  kind-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Create kind cluster
    - name: Create kind cluster
      uses: helm/kind-action@v1.8.0
      with:
        version: v0.22.0
        node_image: kindest/node:v1.29.0

    # Build Docker image and load into kind
    - name: Build Docker image
      run: |
        docker build -t cloud-demo:local .
        kind load docker-image cloud-demo:local

    # Deploy Kubernetes manifests
    - name: Deploy app
      run: |
        kubectl apply -f namespace.yaml
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl rollout status deployment/cloud-demo -n cloud-demo

    # Test service
    - name: Test service
      run: |
        kubectl wait --for=condition=available deployment/cloud-demo -n cloud-demo --timeout=120s
        POD_NAME=$(kubectl get pod -n cloud-demo -l app=cloud-demo -o jsonpath="{.items[0].metadata.name}")
        kubectl port-forward -n cloud-demo pod/$POD_NAME 8080:80 > port-forward.log 2>&1 &
        sleep 10
        curl -v http://127.0.0.1:8080
